var webpack=require("webpack");

module.exports={
    module:{
        rules:[
            {
                test:/\.js[x]?$/,
                loader:'babel-loader',
                exclude:/node_modules/
            },
            {
                test:/\.vue$/,
                loader:'vue-loader'
            },
            {
                test:/\.css$/,
                loader:['style-loader','css-loader']
            },
            {
                test:/\.(eot|svg|ttf|woff|woff2)(\?\S*)$/,
                loader:'url-loader',
                query:{
                    name:'fonts/[name].[chunkhash:7].[ext]'
                }
            },
            {
                test:/\.(png|jpe?g|svg|gif)(\?\S*)?$/,
                loader:'url-loader',
                query:{
                    limit:8192,
                    name:'img/[name].[chunkhash:7].[ext]'
                }
            },
        ]
    },
    resolve:{
        extensions:['.js','.jsx'],
        alias:{
            'vue$':'vue/dist/vue.min.js'
        }
    }
}